@startuml

package nameserver {
    package clusterAddrTable {
        entity ClusterName2BrokerName {
            - clusterName: String
            --
            - brokerName: String
        }
    }

    package brokerAddrTable {
        entity BrokerName2BrokerId {
            - brokerName: String
            --
            - brokerId: long
        }

        entity "BrokerEndpoint: BrokerData" as BrokerId2BrokerEndpoint {
            - brokerId: long
            --
            - brokerEndpoint: String
        }
    }

    package brokerLiveTable {
        entity BrokerEndpoint2BrokerChannel {
            - brokerEndpoint: String
            --
            - brokerChannel: Channel
        }

        entity "BrokerAlive: BrokerLiveInfo" as BrokerAlive {
            - brokerChannel: Channel
            --
            - updateTime: long
            - dataVersion: DataVersion
            - haEndpoint: String
        }
    }

    package topicQueueTable {
        entity BrokerTopic2BrokerName {
            - topic: String
            --
            - brokerName: String
        }

        entity BrokerQueue {
            - brokerName: String
            --
            - readNum: int
            - writeNum: int
        }
    }

    ClusterName2BrokerName::brokerName --o BrokerName2BrokerId
    BrokerName2BrokerId::brokerId --o BrokerId2BrokerEndpoint
    BrokerId2BrokerEndpoint::brokerEndpoint --o BrokerEndpoint2BrokerChannel
    BrokerEndpoint2BrokerChannel::brokerChannel --o BrokerAlive
    BrokerTopic2BrokerName::brokerName --o BrokerQueue
}

package client {
    entity Producer {
        - group: String
        - topic: String
    }
    entity Consumer {
        - group: String
        - topic: String
    }
    entity Queue {
        - readNum: int
        - writeNum: int
    }

    entity TopicRouteData {
        - topic: String
        --
        - queues: List<Queue>
        - brokers: List<BrokerEndpoint>
    }
    entity BrokerEndpoint {
        - brokerName: String
        - brokerId: long
        - brokerEndpoint: String
    }

    Consumer::topic --o TopicRouteData
    Producer::topic --o TopicRouteData
    TopicRouteData::queues  --o Queue
    TopicRouteData::brokers --o BrokerEndpoint

}

@enduml