@startuml

namespace broker {
    entity Topic {
        - topic: String
        --
        - readNum: int
        - writeNum: int
    }
}

namespace client {
    entity ProducerPublish {
        - topic: String
        --
        - queueId: int
    }

    entity ConsumerSubscribe {
        - topic: String
        --
        - tags: Set<String>
    }

    entity TopicRoute {
        - topic: String
        --
        - queues: List<Queue>
        - brokers: List<BrokerEndpoint>
    }
    entity Queue {
        - brokerName: String
        --
        - readNum: int
        - writeNum: int
    }

    entity BrokerEndpoint {
        - brokerName
        --
        - brokerId
        - brokerEndpoint
    }

    ConsumerSubscribe::topic --o TopicRoute
    ProducerPublish::topic --o TopicRoute
    TopicRoute::queues  --o Queue
    TopicRoute::brokers --o BrokerEndpoint
    Queue::brokerName --o BrokerEndpoint
}

namespace nameserver {
    entity Cluster {
        - clusterName: String
        --
        - brokerName: String
    }

    entity BrokerEndpoint {
        - brokerName: String
        --
        - brokerId: long
        - brokerEndpoint: String
    }

    entity BrokerAliveMap {
        - brokerEndpoint: String
        --
        - brokerChannel: Channel
        - updateTime: long
        - dataVersion: DataVersion
        - haEndpoint: String
    }

    entity TopicRoute {
        - topic: String
        --
        - brokerName: String
    }

    entity Queue {
        - brokerName: String
        --
        - readNum: int
        - writeNum: int
    }

    Cluster::brokerName --o BrokerEndpoint
    BrokerEndpoint::brokerEndpoint --o BrokerAliveMap
    TopicRoute::brokerName --o BrokerEndpoint
    TopicRoute::brokerName --o Queue
}

nameserver.BrokerEndpoint::brokerName --o client.Queue::brokerName
nameserver.TopicRoute::topic --o client.TopicRoute::topic

nameserver.TopicRoute::topic -- broker.Topic::topic
'nameserver.BrokerEndpoint -o broker
'nameserver.Cluster -o broker

@enduml