@startuml

namespace nameserver {
    entity ClusterMap {
        - clusterName: String
        --
        - brokerName: String
    }

    entity BrokerEndpointMap {
        - brokerName
        --
        - brokerId
        - brokerEndpoint
    }

    entity BrokerAliveMap {
        - brokerEndpoint: String
        --
        - brokerChannel: Channel
        - updateTime: long
        - dataVersion: DataVersion
        - haEndpoint: String
    }

    entity TopicBrokerMap {
        - topic: String
        --
        - brokerName: String
    }

    entity BrokerQueue {
        - brokerName: String
        --
        - readNum: int
        - writeNum: int
    }

    ClusterMap::brokerName --o BrokerEndpointMap
    BrokerEndpointMap::brokerEndpoint --o BrokerAliveMap
    TopicBrokerMap::brokerName --o BrokerEndpointMap
    TopicBrokerMap::brokerName -o BrokerQueue
}

namespace broker {

}

namespace client {
    entity ProducerPublish {
        - topic: String
        --
        - queueId: int
    }
    entity ProducerMap {
        - group: String
        --
        - topic: ProducerPublish
    }

    entity ConsumerMap {
        - group: String
        --
        - topic: ConsumerSubscribe
    }
    entity ConsumerSubscribe {
        - topic: String
        --
        - tags: Set<String>
    }
    ProducerMap::topic --o ProducerPublish
    ConsumerMap::topic --o ConsumerSubscribe

    entity TopicRouteMap {
        - topic: String
        --
        - queues: List<BrokerQueue>
        - brokers: List<BrokerEndpoint>
    }
    entity BrokerQueue {
        - brokerName: String
        --
        - readNum: int
        - writeNum: int
    }

    entity BrokerEndpointMap {
        - brokerName
        --
        - brokerId
        - brokerEndpoint
    }

    ConsumerMap::topic --o TopicRouteMap
    ProducerMap::topic --o TopicRouteMap
    TopicRouteMap::queues  --o BrokerQueue
    TopicRouteMap::brokers -o BrokerEndpointMap
    BrokerQueue::brokerName -o BrokerEndpointMap
}

nameserver.BrokerEndpointMap::brokerName -o client.BrokerQueue::brokerName
nameserver.TopicBrokerMap::topic -o client.TopicRouteMap::topic

@enduml